# Generated by Django 3.2.9 on 2021-12-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211228_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcuts',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
